#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# remove any existing nvim config and link latest
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
	rm -rf ~/.config/nvim/$f
	ln -s ~/dev/repos/dotfiles/$f ~/.config/nvim/$f
done
